#!/bin/bash

yay -S --needed --answerdiff=None --noconfirm \
	python2 python3 python-i3-py \
	nerd-fonts-hack polybar papirus-icon-theme \
	picom i3-gaps feh toilet \
	alacritty tmux \
	fish fundle-git \
        rclone \
        rofi htop nano firefox \
	openssh \
        pavucontrol pulseaudio-ctl \
	network-manager-applet networkmanager \
	git \
        net-tools \
        ttf-dejavu \
        xorg-server \
        xorg-apps \
        xorg-server-xvfb \
        xorg-xinit \
	xrdp xorgxrdp \
	archur

# install those plugins
fish -c "fundle install"

archur -o ~/.wallpaper.png -t black --text $HOSTNAME
