#!/bin/bash

yay -S --needed --answerdiff=None --noconfirm \
	python2 python-i3-py \
	nerd-fonts-hack polybar xorg-xbacklight papirus-icon-theme \
	fish fundle-git \
        rclone \
        xcompmgr \
        pavucontrol pulseaudio-ctl \
        i3lockmore \
        arandr arandr-indicator

# install those plugins
fish -c "fundle install"
